Send empty GNSS messages for missed observations
christianrowlands/android-network-survey pull request #14
Opened 2022-09-07 16:37 UTC by dtufekcic

Generate and send empty GNSS messages for any missed GNSS observations

2022-09-10 15:35 UTC, christianrowlands requested changes
One super minor change, but otherwise it looks great! Thanks for making this change.

2022-09-10 15:35 UTC, christianrowlands commented on networksurvey/src/main/java/com/craxiom/networksurvey/services/NetworkSurveyService.java
> +    }
I think we can get away from making the `gnssScanRateMs` static. The `gnssScanRateMs` is already in the `SurveyRecordProcessor`, and if you want to provide a single source of truth for calculating the GNSS timeout, then you could add a static method to a utils class, and pass in the `gnssScanRateMs` as a parameter. I think I like that more than changing the instance variable to a static. However, I might be missing a nuance here.

2022-09-13 15:34 UTC, eliza-mae-alcaraz approved these changes

2022-09-20 15:42 UTC, christianrowlands approved these changes

2022-09-20 15:43 UTC, merged